apiVersion: apps/v1
kind: Deployment
metadata:
  name: iiif-gateway-deployment
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: iiif-gateway
          imagePullPolicy: Never